language: python
python:
- '2.7'

install:
- pip install -r test-requirements.txt
- pip install coveralls
- pip install pyflakes==1.2.3
- pip install pylint==1.5.6
- pip install yapf==0.10.0
- pip install google-compute-engine

script:
- ./build
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh

after_success:
- coveralls

before_install:
- $TRAVIS_BUILD_DIR/travis/decrypt.sh
  "$encrypted_ea5d7bea5193_key" "$encrypted_ea5d7bea5193_iv"
  keys/service-accounts.tar.enc /tmp/service-accounts.tar /tmp

# These directories will be cached on successful "script" builds, and restored,
# if available, to save time on future builds.
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

deploy:
# Sandbox.
- provider: script
  script: $TRAVIS_BUILD_DIR/deploy_prometheus_targets.sh mlab-sandbox
  skip_cleanup: true
  on:
    # TODO: update repo
    repo: m-lab/operator
    # Consider all branches and match using the condition. By default
    # "all_branches" is false, and the condition is ignored.
    all_branches: true
    # Only deploy after merging to master.
    condition: $TRAVIS_BRANCH == master || $TRAVIS_BRANCH == sandbox-*
